ADDED: Team Page
POSUA-NITS/Posua-2024 pull request #10
Opened 2024-03-21 13:05 UTC by satyaaa111

1. developer card is added
2. patron card is added
3. team page is added
4. made the layout of team page

2024-03-21 15:49 UTC, Himangshu-101 requested changes
1. Implement a slider in mobile view for the cards
2. Give proper drop shadows for each card
3. Give rotation in 'Japi'

2024-03-24 15:52 UTC, satyaaa111 commented
1.review mentioned are done

2024-03-24 15:53 UTC, satyaaa111 commented
> 1. Implement a carousel/slider in mobile view for the cards
> 2. Give proper drop shadows for each card
> 3. Give rotation in 'Japi'

"These are done"

2024-03-24 17:01 UTC, Himangshu-101 approved these changes

2024-03-24 17:01 UTC, merged